from Functions import SuffixTree

if __name__ == '__main__':
    t = SuffixTree()
    t.add_sequence('abananaandanananasandtwobananasandanananas')
    t.add_sequence('a', 'parallel1')
    t.add_sequence('ab', 'parallel2')
    t.add_sequence('ba', 'parallel1')
    t.add_sequence('ab', 'parallel2')
    t.add_sequence('bb', 'parallel1')
    t.add_sequence('ab', 'parallel2')
    t.add_sequence('ab', 'parallel1')
    t2 = SuffixTree()
    t2.add_sequence('a', 'parallel1bis')
    t2.add_sequence('ab', 'parallel2bis')
    t2.add_sequence('ba', 'parallel1bis')
    t2.add_sequence('ba', 'parallel2bis')
    t2.add_sequence('ba', 'parallel1bis')
    t2.add_sequence('ba', 'parallel2bis')
    t.add_sequence('abaabaab', 'ds1')
    t.add_sequence('aabaabaab', 'ds1')
    t.add_sequence('aabaaba', 'ds2')
    t.add_sequence('a', 'ds1')
    t.add_sequence('aab', 'ds1')
    t.add_sequence('aabaa', 'ds1')
    t.add_sequence('baabaaa', 'ds1')
    t.add_sequence('baaba', 'ds1')
    t.add_sequence('abaaab', 'ds2')
    t.add_sequence('aabaab', 'ds2')
    t.add_sequence('aaba', 'ds2')
    t.add_sequence('ab', 'ds1')
    t.add_sequence('c', 'ds1')
    t.add_sequence('abananaandananana', 'monkey1')
    t.add_sequence('s', 'monkey1')
    t.add_sequence('andtwobananas', 'ape1')
    t.add_sequence('andtwoananases', 'ape1')
    t.add_sequence('v', 'monkey1')
    t.add_sequence('mis', 'state')
    t.add_sequence('siss', 'state')
    t.add_sequence('ippi', 'state')
    t.draw_tree()
